# Generated by Django 5.2.4 on 2025-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
